version: 2.0

commands:
  install_dependencies:
    description: "Install development dependencies."
    steps:
      - run: composer install
      - run: npm ci
  mkdir_artifacts:
    description: "Make Artifacts directory"
    steps:
      - run:
          command: |
            [ ! -d "/tmp/artifacts" ] && mkdir /tmp/artifacts &>/dev/null

executors:
  base:
    docker:
      - image: circleci/buildpack-deps:latest
    working_directory: /tmp
  php_node:
    docker:
      - image: circleci/php:7.3.3-stretch-node-browsers
    working_directory: /tmp/theme
  python:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: /tmp

jobs:
  checkout:
    executor: base
    steps:
      - checkout:
          path: theme
      - persist_to_workspace:
          root: /tmp
          paths:
            - theme

  standards:
    executor: php_node
    steps:
      - attach_workspace:
          at: /tmp
      - install_dependencies
      - run: composer phpcs
      - run: npm run lint:css
      - run: npm run lint:js

  bundle:
    executor: php_node
    steps:
      - attach_workspace:
          at: /tmp
      - run: npm ci
      - run: npm run zip
      - mkdir_artifacts
      - run: mv ./*.zip /tmp/artifacts/.
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts
            - theme
      - store_artifacts:
          path: /tmp/artifacts/

  create_data_file:
    executor: php_node
    steps:
      - attach_workspace:
          at: /tmp
      - run: npm run prep:piservice /tmp/artifacts
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts

  deploy_studiopress:
    executor: python
    parameters:
      install_name:
        type: string
        default: myspressstg
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f2:c5:53:4d:39:eb:ba:72:06:4d:fc:48:7c:5a:0f:df"
      - attach_workspace:
          at: /tmp
      - run:
          command: |
            ARTIFACT_FILE=$(find /tmp/artifacts -type f -name *.zip -printf "%f\n")
            DEST_PATH=home/wpe-user/sites/<< parameters.install_name >>/wp-content/uploads/member-access/${ARTIFACT_FILE}
            DEST_HOST=<< parameters.install_name >>@<< parameters.install_name >>.ssh.wpengine.net
            scp /tmp/artifacts/${ARTIFACT_FILE} ${DEST_HOST}/${DEST_PATH}


  deploy_s3:
    executor: python
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Set S3_PATH env variable"
          command: |
            echo "export S3_PATH=$(grep 'textdomain' /tmp/theme/package.json | awk -F: '{print $2}' | sed 's/^\s//' | sed 's/\"//g')" >> ${BASH_ENV}
      - aws-s3/sync:
          from: "/tmp/artifacts/"
          to: "s3://update.atomicblocks.com/themes/${S3_PATH}/"

workflows:
  version: 2
  checks:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: master
      - standards:
          requires:
            - checkout
          filters:
            branches:
              ignore: master

  branch_deploy:
    jobs:
      - checkout:
          filters:
            branches:
              only: master
      - standards:
          requires:
            - checkout
          filters:
            branches:
              only: master
      - bundle:
          requires:
            - standards
          filters:
            branches:
              only: master
      - create_data_file:
          requires:
            - bundle
          filters:
            branches:
              only: master
      - deploy_studiopress:
          install_name: myspressstg
          requires:
            - create_data_file
          filters:
            branches:
              only: master

  tag_deploy:
    jobs:
      - checkout:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - standards:
          requires:
            - checkout
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - bundle:
          requires:
            - standards
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - create_data_file:
          requires:
            - bundle
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deploy_studiopress:
          install_name: myspress
          requires:
            - create_data_file
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deploy_s3:
          context: wpe-product-info-aws
          requires:
            - create_data_file
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

orbs:
  aws-s3: circleci/aws-s3@1.0.0
